### ISSUE TITLE
Drop PyYAML dependency

### ISSUE THREAD

**Issue by notpushkin** [ywu94/python-text-distance#2]
It is rather heavyweight and only includes wheels (binary builds) for Windows, so on Linux/macOS it will be built from source. Considering that it isn't used for anything except the logging config here, perhaps we could drop it altogether?

The usual way to allow configuring loggers for a library is [using named loggers](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library):

```py
# in the library:
import logging
logging.getLogger('pytextdist').addHandler(logging.NullHandler())

# ... later, in the app using the library:
logging.getLogger('pytextdist').addHandler(logging.StreamHandler(...))
```

To make things a bit easier, it is also possible to use `__name__` as the name for the logger, [like the `requests` package does](https://docs.python-guide.org/writing/logging/#logging-in-a-library):

```py
logging.getLogger(__name__).addHandler(logging.NullHandler())
```

What do you think?

**Comment by ywu94** [comment]
Thanks for the suggestion. The reason for having a logging config file is to make it easy to control logging for all modules in one place so I think we should keep the logger config file.

However logging also supports `json` as its config file so one workaround will be to rewrite the logging config file into a json which can be read using Python built-in library.

**Comment by notpushkin** [comment]
I still think it should be the apps authors responsibility. Config file is not the best option for everybody. e. g.:
- a CLI tool might want to vary its config settings based on how many `-v` switches it got
- a GUI application might log into its UI and allow users to change logging settings on the fly
- a [Twelve-Factor](https://12factor.net/config) proponent could prefer to store the whole config in the environment – not that it makes too much sense if there are two or three deploy variations, but some people do that :)

I'd say this code

```py
with open(logger_config_yaml_path, "rt") as f:
    config = yaml.safe_load(f.read())
logging.config.dictConfig(config)
```

belongs in the application itself as it's way too specific.

**Comment by ywu94** [comment]
That makes sense, will remove the dependencies in next version.

**Comment by ywu94** [comment]
Changes made per suggested, thanks again for suggestion.
